fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

bootcamp_admin:
    resource: "@BootcampAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
        
bootcamp_frontend:
    resource: "@BootcampFrontendBundle/Resources/config/routing.yml"
    prefix:   /

    
